### ISSUE TITLE
Model: mc: particle spin

### ISSUE THREAD

**Issue by decibelcooper** [proio-org/proio#12]
Hi Serge (@chekanov),

There is a comment in the mc model file (https://github.com/proio-org/proio/blob/7dd48a9403195bfd77d32c8518b01680acd4b354/model/mc/mc.proto#L24) that the integer spin is "2*spin+1".  Why would it be "+1"?

**Comment by chekanov** [comment]
This was set to be consistent with Pythia8:

 http://home.thep.lu.se/Pythia/pythia82html/ParticleDataScheme.html

**Comment by decibelcooper** [comment]
Okay this makes sense.  I'm not sure why we have this field as sint.  It should be uint.  Could be my mistake in copying things over.
